// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fewuuijsoartxdsmnbal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZld3V1aWpzb2FydHhkc21uYmFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyOTY3MjgsImV4cCI6MjA2Njg3MjcyOH0.8_E0mQOIJ7w6P3nlXhFyYY9leQpQNl3_XChnBJwN1sg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});